// ========== 属性数据 ==========
var TYPES = ["一般","火","水","草","电","冰","格斗","毒","地面","飞行","超能力","虫","岩石","幽灵","龙","恶","钢","妖精"];

var TYPE_COLORS = {
  "一般": "#a8a28c", "火": "#e4722c", "水": "#6399e8", "草": "#63b946",
  "电": "#f1cd2b", "冰": "#86d2d0", "格斗": "#b83c2e", "毒": "#8c3f9c",
  "地面": "#d6b357", "飞行": "#b3a0e8", "超能力": "#ed5c87", "虫": "#91a827",
  "岩石": "#b4943e", "幽灵": "#674e82", "龙": "#653fc9", "恶": "#685041",
  "钢": "#a8abb5", "妖精": "#e897b2"
};

var typeChart = {
  "虫": {"虫":1,"恶":1.5,"龙":1,"电":1,"妖精":0.5,"格斗":0.5,"火":0.5,"飞行":0.5,"幽灵":0.5,"草":1.5,"地面":1,"冰":1,"一般":1,"毒":0.5,"超能":1.5,"岩石":1,"钢":0.5,"水":1},
  "恶": {"虫":1,"恶":0.5,"龙":1,"电":1,"妖精":0.5,"格斗":0.5,"火":1,"飞行":1,"幽灵":1.5,"草":1,"地面":1,"冰":1,"一般":1,"毒":1,"超能":1.5,"岩石":1,"钢":1,"水":1},
  "龙": {"虫":1,"恶":1,"龙":1.5,"电":1,"妖精":0,"格斗":1,"火":1,"飞行":1,"幽灵":1,"草":1,"地面":1,"冰":1,"一般":1,"毒":1,"超能":1,"岩石":1,"钢":0.5,"水":1},
  "电": {"虫":1,"恶":1,"龙":0.5,"电":0.5,"妖精":1,"格斗":1,"火":1,"飞行":1.5,"幽灵":1,"草":0.5,"地面":0,"冰":1,"一般":1,"毒":1,"超能":1,"岩石":1,"钢":1,"水":1.5},
  "妖精": {"虫":1,"恶":1.5,"龙":1.5,"电":1,"妖精":1,"格斗":1.5,"火":0.5,"飞行":1,"幽灵":1,"草":1,"地面":1,"冰":1,"一般":1,"毒":0.5,"超能":1,"岩石":1,"钢":0.5,"水":1},
  "格斗": {"虫":0.5,"恶":1.5,"龙":1,"电":1,"妖精":0.5,"格斗":1,"火":1,"飞行":0.5,"幽灵":0,"草":1,"地面":1,"冰":1.5,"一般":1.5,"毒":0.5,"超能":0.5,"岩石":1.5,"钢":1.5,"水":1},
  "火": {"虫":1.5,"恶":1,"龙":0.5,"电":1,"妖精":1,"格斗":1,"火":0.5,"飞行":1,"幽灵":1,"草":1.5,"地面":1,"冰":1.5,"一般":1,"毒":1,"超能":1,"岩石":0.5,"钢":1.5,"水":0.5},
  "飞行": {"虫":1.5,"恶":1,"龙":1,"电":0.5,"妖精":1,"格斗":1.5,"火":1,"飞行":1,"幽灵":1,"草":1.5,"地面":1,"冰":1,"一般":1,"毒":1,"超能":1,"岩石":0.5,"钢":0.5,"水":1},
  "幽灵": {"虫":1,"恶":0.5,"龙":1,"电":1,"妖精":1,"格斗":1,"火":1,"飞行":1,"幽灵":1.5,"草":1,"地面":1,"冰":1,"一般":0,"毒":1,"超能":1.5,"岩石":1,"钢":1,"水":1},
  "草": {"虫":0.5,"恶":1,"龙":0.5,"电":1,"妖精":1,"格斗":1,"火":0.5,"飞行":0.5,"幽灵":1,"草":0.5,"地面":1.5,"冰":1,"一般":1,"毒":0.5,"超能":1,"岩石":1.5,"钢":0.5,"水":1.5},
  "地面": {"虫":0.5,"恶":1,"龙":1,"电":1.5,"妖精":1,"格斗":1,"火":1.5,"飞行":0,"幽灵":1,"草":0.5,"地面":1,"冰":1,"一般":1,"毒":1.5,"超能":1,"岩石":1.5,"钢":1.5,"水":1},
  "冰": {"虫":1,"恶":1,"龙":1.5,"电":1,"妖精":1,"格斗":1,"火":0.5,"飞行":1.5,"幽灵":1,"草":1.5,"地面":1.5,"冰":0.5,"一般":1,"毒":1,"超能":1,"岩石":1,"钢":0.5,"水":0.5},
  "一般": {"虫":1,"恶":1,"龙":1,"电":1,"妖精":1,"格斗":1,"火":1,"飞行":1,"幽灵":0,"草":1,"地面":1,"冰":1,"一般":1,"毒":1,"超能":1,"岩石":0.5,"钢":0.5,"水":1},
  "毒": {"虫":1,"恶":1,"龙":1,"电":1,"妖精":1.5,"格斗":1,"火":1,"飞行":1,"幽灵":0.5,"草":1.5,"地面":0.5,"冰":1,"一般":1,"毒":0.5,"超能":1,"岩石":0.5,"钢":0,"水":1},
  "超能": {"虫":1,"恶":0,"龙":1,"电":1,"妖精":1,"格斗":1.5,"火":1,"飞行":1,"幽灵":1,"草":1,"地面":1,"冰":1,"一般":1,"毒":1.5,"超能":0.5,"岩石":1,"钢":0.5,"水":1},
  "岩石": {"虫":1.5,"恶":1,"龙":1,"电":1,"妖精":1,"格斗":0.5,"火":1.5,"飞行":1.5,"幽灵":1,"草":1,"地面":0.5,"冰":1.5,"一般":1,"毒":1,"超能":1,"岩石":1,"钢":0.5,"水":1},
  "钢": {"虫":1,"恶":1,"龙":1,"电":0.5,"妖精":1.5,"格斗":1,"火":0.5,"飞行":1,"幽灵":1,"草":1,"地面":1,"冰":1.5,"一般":1,"毒":1,"超能":1,"岩石":1.5,"钢":0.5,"水":0.5},
  "水": {"虫":1,"恶":1,"龙":0.5,"电":1,"妖精":1,"格斗":1,"火":1.5,"飞行":1,"幽灵":1,"草":0.5,"地面":1.5,"冰":1,"一般":1,"毒":1,"超能":1,"岩石":1.5,"钢":0.5,"水":0.5}
};

var WEATHER_PRESETS = [
  { name:"无", types:[], note:"" },
  { name:"大晴天", types:["火"], note:"火" },
  { name:"雨天", types:["水"], note:"水" },
  { name:"雪天", types:["冰"], note:"冰" },
  { name:"沙暴", types:["岩石","地面","钢"], note:"岩石/地面/钢" },
  { name:"电气场地", types:["电"], note:"电" },
  { name:"青草场地", types:["草"], note:"草" },
  { name:"精神场地", types:["超能力"], note:"超能力" },
  { name:"薄雾场地", types:["妖精"], note:"妖精" },
  { name:"乱流", types:["飞行"], note:"飞行" },
  { name:"自定义天气", types:[], note:"自定义" }
];

var MOVE_DB = [
  {name:"疯狂伏特", type:"电", category:"物理", power:120, pinyin:"fkft"},
  {name:"雷电拳", type:"电", category:"物理", power:75, pinyin:"ldq"},
  {name:"电光", type:"电", category:"物理", power:65, pinyin:"dg"},
  {name:"雷击", type:"电", category:"物理", power:130, pinyin:"lj"},
  {name:"伏特攻击", type:"电", category:"物理", power:120, pinyin:"ftgj"},
  {name:"劈开", type:"一般", category:"物理", power:90, pinyin:"pk"},
  {name:"闪焰冲锋", type:"火", category:"物理", power:120, pinyin:"sycf"},
  {name:"火焰拳", type:"火", category:"物理", power:75, pinyin:"hyq"},
  {name:"火焰踢", type:"火", category:"物理", power:85, pinyin:"hyt"},
  {name:"蓄能焰袭", type:"火", category:"物理", power:50, pinyin:"xnyx"},
  {name:"水流裂破", type:"水", category:"物理", power:85, pinyin:"sllp"},
  {name:"攀瀑", type:"水", category:"物理", power:80, pinyin:"pb"},
  {name:"水流喷射", type:"水", category:"物理", power:40, pinyin:"slps"},
  {name:"贝壳刃", type:"水", category:"物理", power:75, pinyin:"bkr"},
  {name:"强力鞭打", type:"草", category:"物理", power:120, pinyin:"qlbd"},
  {name:"叶刃", type:"草", category:"物理", power:90, pinyin:"yr"},
  {name:"种子炸弹", type:"草", category:"物理", power:80, pinyin:"zzzd"},
  {name:"木槌", type:"草", category:"物理", power:120, pinyin:"mc"},
  {name:"冰柱坠击", type:"冰", category:"物理", power:85, pinyin:"bzzj"},
  {name:"冰冻拳", type:"冰", category:"物理", power:75, pinyin:"bdq"},
  {name:"冰砾", type:"冰", category:"物理", power:40, pinyin:"bl"},
  {name:"近身战", type:"格斗", category:"物理", power:120, pinyin:"jsz"},
  {name:"飞膝踢", type:"格斗", category:"物理", power:130, pinyin:"fxt"},
  {name:"吸取拳", type:"格斗", category:"物理", power:75, pinyin:"xqq"},
  {name:"劈瓦", type:"格斗", category:"物理", power:75, pinyin:"pw"},
  {name:"发劲", type:"格斗", category:"物理", power:60, pinyin:"fj"},
  {name:"垃圾射击", type:"毒", category:"物理", power:120, pinyin:"ljsj"},
  {name:"毒击", type:"毒", category:"物理", power:80, pinyin:"dj"},
  {name:"地震", type:"地面", category:"物理", power:100, pinyin:"dz"},
  {name:"十万马力", type:"地面", category:"物理", power:95, pinyin:"swml"},
  {name:"跺脚", type:"地面", category:"物理", power:75, pinyin:"dj"},
  {name:"勇鸟猛攻", type:"飞行", category:"物理", power:120, pinyin:"ynmg"},
  {name:"飞翔", type:"飞行", category:"物理", power:90, pinyin:"fx"},
  {name:"燕返", type:"飞行", category:"物理", power:60, pinyin:"yf"},
  {name:"意念头槌", type:"超能力", category:"物理", power:80, pinyin:"yntc"},
  {name:"精神利刃", type:"超能力", category:"物理", power:70, pinyin:"jslr"},
  {name:"急速折返", type:"虫", category:"物理", power:70, pinyin:"jszf"},
  {name:"吸血", type:"虫", category:"物理", power:80, pinyin:"xx"},
  {name:"猛扑", type:"虫", category:"物理", power:80, pinyin:"mp"},
  {name:"十字剪", type:"虫", category:"物理", power:80, pinyin:"szj"},
  {name:"岩崩", type:"岩石", category:"物理", power:75, pinyin:"yb"},
  {name:"尖石攻击", type:"岩石", category:"物理", power:100, pinyin:"jsgj"},
  {name:"暗影爪", type:"幽灵", category:"物理", power:70, pinyin:"ayz"},
  {name:"潜灵奇袭", type:"幽灵", category:"物理", power:90, pinyin:"qlqx"},
  {name:"影子偷袭", type:"幽灵", category:"物理", power:40, pinyin:"yztx"},
  {name:"逆鳞", type:"龙", category:"物理", power:120, pinyin:"nl"},
  {name:"龙爪", type:"龙", category:"物理", power:80, pinyin:"lz"},
  {name:"咬碎", type:"恶", category:"物理", power:80, pinyin:"ys"},
  {name:"突袭", type:"恶", category:"物理", power:70, pinyin:"tx"},
  {name:"欺诈", type:"恶", category:"物理", power:95, pinyin:"qz"},
  {name:"拍落", type:"恶", category:"物理", power:65, pinyin:"pl"},
  {name:"铁头", type:"钢", category:"物理", power:80, pinyin:"tt"},
  {name:"彗星拳", type:"钢", category:"物理", power:90, pinyin:"hxq"},
  {name:"子弹拳", type:"钢", category:"物理", power:40, pinyin:"zdq"},
  {name:"嬉闹", type:"妖精", category:"物理", power:90, pinyin:"xn"},
  {name:"舍身冲撞", type:"一般", category:"物理", power:120, pinyin:"sscz"},
  {name:"终极冲击", type:"一般", category:"物理", power:150, pinyin:"zjcj"},
  {name:"泰山压顶", type:"一般", category:"物理", power:85, pinyin:"tsyd"},
  {name:"电光一闪", type:"一般", category:"物理", power:40, pinyin:"dgys"},
  {name:"十万伏特", type:"电", category:"特殊", power:90, pinyin:"swft"},
  {name:"打雷", type:"电", category:"特殊", power:110, pinyin:"dl"},
  {name:"伏特替换", type:"电", category:"特殊", power:70, pinyin:"ftth"},
  {name:"电磁炮", type:"电", category:"特殊", power:120, pinyin:"dcp"},
  {name:"放电", type:"电", category:"特殊", power:80, pinyin:"fd"},
  {name:"喷射火焰", type:"火", category:"特殊", power:90, pinyin:"pshy"},
  {name:"大字爆炎", type:"火", category:"特殊", power:110, pinyin:"dzby"},
  {name:"过热", type:"火", category:"特殊", power:130, pinyin:"gr"},
  {name:"水炮", type:"水", category:"特殊", power:110, pinyin:"sp"},
  {name:"冲浪", type:"水", category:"特殊", power:90, pinyin:"cl"},
  {name:"热水", type:"水", category:"特殊", power:80, pinyin:"rs"},
  {name:"飞叶风暴", type:"草", category:"特殊", power:130, pinyin:"fyfb"},
  {name:"能量球", type:"草", category:"特殊", power:90, pinyin:"nlq"},
  {name:"终极吸取", type:"草", category:"特殊", power:75, pinyin:"zjxq"},
  {name:"日光束", type:"草", category:"特殊", power:120, pinyin:"rgs"},
  {name:"冰冻光束", type:"冰", category:"特殊", power:90, pinyin:"bdgs"},
  {name:"暴风雪", type:"冰", category:"特殊", power:110, pinyin:"bfx"},
  {name:"冷冻干燥", type:"冰", category:"特殊", power:70, pinyin:"ldgz"},
  {name:"精神强念", type:"超能力", category:"特殊", power:90, pinyin:"jsqn"},
  {name:"精神冲击", type:"超能力", category:"特殊", power:80, pinyin:"jscj"},
  {name:"暗影球", type:"幽灵", category:"特殊", power:80, pinyin:"ayq"},
  {name:"祸不单行", type:"幽灵", category:"特殊", power:65, pinyin:"hbdx"},
  {name:"龙星群", type:"龙", category:"特殊", power:130, pinyin:"lxq"},
  {name:"龙之波动", type:"龙", category:"特殊", power:85, pinyin:"lzbd"},
  {name:"恶之波动", type:"恶", category:"特殊", power:80, pinyin:"ezbd"},
  {name:"大声咆哮", type:"恶", category:"特殊", power:55, pinyin:"dspx"},
  {name:"加农光炮", type:"钢", category:"特殊", power:80, pinyin:"jngp"},
  {name:"月亮之力", type:"妖精", category:"特殊", power:95, pinyin:"ylzl"},
  {name:"魔法闪耀", type:"妖精", category:"特殊", power:80, pinyin:"mfsy"},
  {name:"污泥炸弹", type:"毒", category:"特殊", power:90, pinyin:"wnzd"},
  {name:"污泥波", type:"毒", category:"特殊", power:95, pinyin:"wnb"},
  {name:"破坏光线", type:"一般", category:"特殊", power:150, pinyin:"phgx"},
  {name:"三角攻击", type:"一般", category:"特殊", power:80, pinyin:"sjgj"},
  {name:"巨声", type:"一般", category:"特殊", power:90, pinyin:"js"},
  {name:"空气斩", type:"飞行", category:"特殊", power:75, pinyin:"kqz"},
  {name:"暴风", type:"飞行", category:"特殊", power:110, pinyin:"bf"},
  {name:"剑舞", type:"一般", category:"变化", power:0, buffType:"attack", buffPower:2.0, pinyin:"jw"},
  {name:"龙舞", type:"龙", category:"变化", power:0, buffType:"attack", buffPower:1.5, pinyin:"lw"},
  {name:"诡计", type:"恶", category:"变化", power:0, buffType:"special", buffPower:2.0, pinyin:"gj"},
  {name:"冥想", type:"超能力", category:"变化", power:0, buffType:"special", buffPower:1.5, pinyin:"mx"},
  {name:"健美", type:"格斗", category:"变化", power:0, buffType:"attack", buffPower:1.5, pinyin:"jm"},
  {name:"生长", type:"一般", category:"变化", power:0, buffType:"both", buffPower:1.5, pinyin:"sz"},
  {name:"蝶舞", type:"虫", category:"变化", power:0, buffType:"special", buffPower:1.5, pinyin:"dw"},
  {name:"大晴天", type:"火", category:"变化", power:0, buffType:"weather", buffPower:0, pinyin:"dqt"},
  {name:"求雨", type:"水", category:"变化", power:0, buffType:"weather", buffPower:0, pinyin:"qy"},
  {name:"冰雹", type:"冰", category:"变化", power:0, buffType:"weather", buffPower:0, pinyin:"bb"},
  {name:"沙暴", type:"岩石", category:"变化", power:0, buffType:"weather", buffPower:0, pinyin:"sb"},
  {name:"电气场地", type:"电", category:"变化", power:0, buffType:"weather", buffPower:0, pinyin:"dqcd"},
  {name:"青草场地", type:"草", category:"变化", power:0, buffType:"weather", buffPower:0, pinyin:"qccd"},
  {name:"精神场地", type:"超能力", category:"变化", power:0, buffType:"weather", buffPower:0, pinyin:"jscd"},
  {name:"薄雾场地", type:"妖精", category:"变化", power:0, buffType:"weather", buffPower:0, pinyin:"bwcd"}
];